### ISSUE TITLE
Password reset email error

### ISSUE THREAD

**Issue by HarryDearing** [wsvincent/djangoforbeginners#1]
Dear Mr. Vincent,

I have learned so much from your Django for Beginners book and really appreciate the detail and thoroughness. Today, I am stuck in Chapter 12. When I create the password_reset_email.html file and run it, I get this error:
-----------------------------------------------------
Request Method: | POST
-- | --
http://127.0.0.1:8000/users/password_reset/
2.1
NoReverseMatch
Reverse for 'password_reset_confirm' with keyword arguments '{'uid64': 'MQ', 'token': '4z2-45d90f90992977986034'}' not found. 1 pattern(s) tried: ['users\\/reset\\/(?P<uidb64>[^/]+)\\/(?P<token>[^/]+)\\/$']
/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/lib/python3.6/site-packages/django/urls/resolvers.py  in _reverse_with_prefix, line 622
/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/bin/python
3.6.5
['/home/harry/Desktop/customuser',  '/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/lib/python36.zip',  '/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/lib/python3.6',  '/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/harry/.local/share/virtualenvs/customuser-H8-7Wb0B/lib/python3.6/site-packages']
Sun, 26 Aug 2018 14:05:00 +0000
------------------------------------------------------------------------
I did not get the error when I used the Django provided html file. I am wondering if the url is not being created somehow or if the url path is not being parsed due to the failure to include it. Your advice on this would be much appreciated. For now, I am going to move on by continuing to use the default html file as done earlier in the chapter. The subject title change is working which seems strange.

Your help is much appreciated.

Thanks,
Harry Dearing

**Comment by wsvincent** [comment]
Hi Harry,

I'm a little late responding but I hope I can still help. Your instinct that a url issue was to blame would be my first guess too. Assuming you have `get_absolute_url` in your models.py, a misconfigured urls.py is usually the culprit here.

I'm curious if you solved the issue in the interim? Please feel free to let me know directly at will@wsvincent.com.

Best wishes,

Will

**Comment by walkersorlie** [comment]
Hi Will,

I am having the same problem (I think) as the original poster. I have included the `django.contrib.auth.urls` in my URLconf, and the views are working up until the password_reset_confirm view. I have the email with a reset password link, but when I paste in the URL and try to go there, Django seems to start url matching for `registration/reset/<uidb64>/<token>/`, but then  changes to try matching for `registration/reset/<uidb64>/set-password` and throws `NoReverseMatch at /registration/reset/MQ/set-password/`. Any ideas of what's going on?

Thanks,
Walker

**Comment by walkersorlie** [comment]
Hi Will,

I am having the same problem (I think) as the original poster. I have included the `django.contrib.auth.urls` in my URLconf, and the views are working up until the password_reset_confirm view. I have the email with a reset password link, but when I paste in the URL and try to go there, Django seems to start url matching for `registration/reset/<uidb64>/<token>/`, but then  changes to try matching for `registration/reset/<uidb64>/set-password` and throws `NoReverseMatch at /registration/reset/MQ/set-password/`. Any ideas of what's going on?

Thanks,
Walker
