### ISSUE TITLE
Wrong Link for Login after Password reset CH.11 P 244

### ISSUE THREAD

**Issue by weirdworkshop** [wsvincent/djangoforbeginners#10]
Chapter 11 Page 244 
After resetting the password for the user I click on the "Log In" Link but am taken to
http://127.0.0.1:8000/accounts/login/
and not http://127.0.0.1:8000/users/login/ 

Which gives a 404 Page with  error message.
`

Using the URLconf defined in newspaper_project.urls, Django tried these URL patterns, in this order:

    1. admin/
    2. users/
    3. users/
    4. [name='home']

The current path, accounts/login/, didn't match any of these.`

**Comment by wsvincent** [comment]
Hmm. Just checked the official source code and it works correctly. I suspect your `urls.py` file is slightly off. Please check again vs the official code!

**Comment by RichP** [comment]
I'm getting the same issue.  The completed code from page 244 does work.  However in the book page 240 before writing the new templates it says "click on 'Log in' link and use your new password".  This doesn't work as the default template links to  accounts/login/ instead of  users/login/
