### ISSUE TITLE
`.env` not work in Windows

### ISSUE THREAD

**Issue by Rafeqm** [wsvincent/djangoforbeginners#100]
In the book, `.env` uses `export` which is a Unix command. How to make this work on Windows?

**Comment by wsvincent** [comment]
Hi @Rafeqm,

Good question! I believe using `set` or `$Env:` in place of `export` should do the trick. Currently working through it myself.

**Comment by wsvincent** [comment]
I'm almost through all this. I think it was incorrect on my part to recommend the use of `export`. If the .env file simply has `DEBUG=True` for example, that works on both macOS and Windows.

The use of export works on macOS cause Linux but is intended to set not just for current shell but all processes started from shell. It seems overkill therefore. Will confirm soon but that's where I'm at currently.

**Comment by wsvincent** [comment]
I appreciate you bringing this up by the way. Clearly I've gone quite far by just using "export" without a deeper understanding of it. Much of web development is like this (very abstract that is) and it's only when someone asks a good question, as you did, that I'm forced to go deeper on topics.

**Comment by wsvincent** [comment]
https://forum.djangoproject.com/t/env-files-and-export/11059/2

Ok, so basically leave off the `export` command in the `.env` file. I'm making this change to the 4.0 edition that's about to go out. Thanks again for raising the issue.

**Comment by Rafeqm** [comment]
Sorry, but it doesn't work either on local or deployment to Heroku. Do you think the problem is on `environs` package? Because setting environment variables in `.env` files with format `variable=value` works well with other known packages like `python-dotenv` (which also `environs` dependency). All became messed up after going through Chapter 16 ☹️ (I read dfb-3.1). I really wanna finish this book.

**Comment by Rafeqm** [comment]
Sorry, but it doesn't work either on local or deployment to Heroku. Do you think the problem is on `environs` package? Because setting environment variables in `.env` files with format `variable=value` works well with other known packages like `python-dotenv` (which also `environs` dependency).

All became messed up after going through Chapter 16 ☹️ (I read dfb-3.1). I really wanna finish this book.
