### ISSUE TITLE
ch1 - broken link

### ISSUE THREAD

**Issue by memilanuk** [wsvincent/djangoforbeginners#107]
The link about the Django project adopting `black` once it's out of beta goes to a 404 page.

https://github.com/django/deps/blob/main/accepted/0008-black.rst

**Comment by wsvincent** [comment]
Ah, yes. Good catch. Black moved out of beta just recently. Not very good that it 404s but just a simple repo for DEPS I guess. I'll update the text and the link.

https://github.com/django/deps/blob/main/final/0008-black.rst
