### ISSUE TITLE
could i make some changes and suggest , let me know if i can do 

### ISSUE THREAD

**Issue by satyam4484** [wsvincent/djangoforbeginners#110]

**Comment by wsvincent** [comment]
I'm always open to feedback if you have read the book and have some.

**Comment by satyam4484** [comment]
maybe the folder structure can be changed and also in the setting file  we can use ` BASE_DIR / 'templates'   `  instead of  ` str(BASE_DIR.joinpath("templates")) ` and little work in the UI section can be also be there by using the bootstrap

**Comment by satyam4484** [comment]
Let me know if you would like to do some changes.

**Comment by wsvincent** [comment]
Hi @satyam4484,

I think you're right about the `templates` code could be a little cleaner. I'd love to hear more suggestions either here or via email directly.

-Will

**Comment by wsvincent** [comment]
Closing this for now since future suggestions can be made directly.
