### ISSUE TITLE
chapter 5 / blog test

### ISSUE THREAD

**Issue by greener2015** [wsvincent/djangoforbeginners#12]
I am getting the following error running a test.
 
(blog) C:\Users\tpdzaja\Documents\Dev\django\blog>python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
...F
======================================================================
FAIL: test_string_representation (blog.tests.BlogTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\tpdzaja\Documents\Dev\django\blog\blog\tests.py", line 25, in test_string_representation
    self.assertEqual(str(post), post.title)
AssertionError: 'Post object (None)' != 'A sample title'
- Post object (None)
+ A sample title

----------------------------------------------------------------------
Ran 4 tests in 1.743s

I copied the test file from the GitHub. 
The application runs but I still would like to trace the failed test. 
Why did it fail?
What should I check?

**Comment by deadthoma5** [comment]
Can you copy/paste your models.py that contains the Post object?

I had a similar error in my test for this chapter, but in my case, I made a typo in my tests.py that caused my test to not create my Post object as expected.

**Comment by wsvincent** [comment]
Hi y'all...I'm pretty sure the code works. I suspect a whitespace issue somehow.

**Comment by greener2015** [comment]
Hello, 
I checked and it was typo as Thomas stated. 
Thank you for responding. 
C
