### ISSUE TITLE
SystemCheckError: System check identified some issues

### ISSUE THREAD

**Issue by bousejin** [wsvincent/djangoforbeginners#135]
Hi Will,

Thank you so much for your awesome book. I was following the book and when I run 'python manage.py runserver' I got the following error:

?: (4_0.E001) As of Django 4.0, the values in the CSRF_TRUSTED_ORIGINS setting must start with a scheme (usually http:// or https://) but found localhost:3000. See the release notes for details.

These are my settings.py variables:

ALLOWED_HOSTS = [".herokuapp.com", "localhost", "127.0.0.1"]

CORS_ORIGIN_WHITELIST = (
    "http://localhost:3000",
    "http://localhost:8000",
)

CSRF_TRUSTED_ORIGINS = ["http://localhost:3000"]

**Comment by wsvincent** [comment]
Hi @bousejin,

Yup, this is a new thing in Django. I am working on a book update. You don't really need to add CSRF_TRUSTED_ORIGINS for localhost but you will need to add whatever the production URL is once you have it. A tricky thing. Thanks for raising an Issue on it.

-Will
