### ISSUE TITLE
ch10-bootstrap-Log In & Sign Up button not dispplayed on the right.

### ISSUE THREAD

**Issue by louisdeco** [wsvincent/djangoforbeginners#138]
Good morning, 

By using my code and your code, the buttons Log In & Sign Up are displayed on the left, next to the Newspaper title. I think that the argument used at the line 40 of the base.html (ch10-bootstrap/templates/base.html) should not be "text-end" as it is supposed to be used with text and inline content and div is neither of those.

Have a nice day,
Louis

**Comment by loganx-26x** [comment]
If anyone's still looking for a solution for this one, paste this inside the body tag:

'''

        <div class="container">
            <header class="p-3 mb-3 border-bottom">
                <div class="container">
                    <div class="d-flex flex-wrap align-items-center justify-content-center
                    justify-content-lg-start">
                    <a class="navbar-brand" href="{% url 'home' %}">Newspaper</a>
                            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center
                                mb-md-0">
                        {% if user.is_authenticated %}
                            <li><a href="#" class="nav-link px-2 link-dark">+ New</a></li>
                            </ul>
                            <div class="dropdown text-end">
                                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.username }}
                                </a>
                                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">
                                    Change password</a></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
                                </li>
                                </ul>
                    </div>
                
                    {% else %}
                        </ul>
                        <div class="text-end">
                            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                        </div>
                    {% endif %}
                    </div>
                </div>
            </header>

            <main>
            {% block content %}
            {% endblock content %}
            </main>
        </div>

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

'''
What's happening here is, we're writing the ul tag on 7th line outside the if statement. Now consider these 2 scenarios:
1) If the {if user.is_authenticated %} block gets executed then the ul tag gets closed after adding the +New button and everything works accordingly.
2) If the {if user.is_authenticated %} block declines then comes the {% else %}  block where our ul tag was never closed.

So what I did was just close the ul tag in {% else %} statement.
Hoping this solves everyone's issues.

**Comment by wsvincent** [comment]
Hi @louisdeco and @loganx-26x,

Thank you both for commenting here and finding the solution. Dealing with closing brackets like `</ul>` is really easy to mess up, and is further compounded by if/else logic. Stuff like this is a big, big reason why a modern text editor is helpful as it will usually highlight such issues as you type then.
