### ISSUE TITLE
calling `get_object()` twice.

### ISSUE THREAD

**Issue by amirsoroush** [wsvincent/djangoforbeginners#156]
Hi,
I noticed that we unnecessarily called `self.get_object()` twice inside `CommentPost` view in these two files:

1. https://github.com/wsvincent/djangoforbeginners/blob/master/ch15-comments/articles/views.py
2. https://github.com/wsvincent/djangoforbeginners/blob/master/ch16-deployment/articles/views.py

```python
class CommentPost(SingleObjectMixin, FormView):
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()         # <------ Here
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.get_object()             # <------ Here
        return reverse("article_detail", kwargs={"pk": article.pk})
```
We can use the `self.object` inside `get_success_url()` method. I'm not sure if it hits the database twice or uses the cached object but at least it does some unnecessary work here to figure out what the object is.

Shall I go ahead and make a PR? or It's not that important?

Thanks for your awesome book btw!

**Comment by wsvincent** [comment]
You are quite right! Nice catch. I'm about to release the 4.2 update actually and I've included this tweak. Thank you :)
