### ISSUE TITLE
Typographical Error on page 104

### ISSUE THREAD

**Issue by samuelerickson977** [wsvincent/djangoforbeginners#173]
At the top of the page the book has the following: "is also slightly insecure. . . we will lock done CSRF_TRUSTED_ORIGINS fully." The problem is with "we will lock done". I believe it is supposed to be "we will lock down".

**Comment by wsvincent** [comment]
Ack! Nice catch @samuelerickson977 . Thank you for taking the time to point it out. Now fixed for this next update.
