### ISSUE TITLE
[4.0] Page 83 Cart before horse error

### ISSUE THREAD

**Issue by NewKidOnTheBlock** [wsvincent/djangoforbeginners#175]
I'm using version 4.0 of _Django for Beginners_.

On page 83, you once more instruct the reader to create a .gitignore file.
Alright. Been there, done that.

After that you say:
"Then run git status again to confirm the .venv directory is being ignored"

```
(.venv) > git status
(.venv) > git add -A
(.venv) > git commit -m "initial commit"
```
Problem: git hasn't been initialized yet, so _git status_ won't work.
For reasons unknown, there is another code block on page 84 with the missing ingredient:

```
(.venv) > git init
(.venv) > git add -A
(.venv) > git commit -m "initial commit"
```

I'd suggest to merge these two code blocks on page 83 & page 84 into one, like this:

```
(.venv) > git init
(.venv) > git status
(.venv) > git add -A
(.venv) > git commit -m "initial commit"

```

**Comment by NewKidOnTheBlock** [comment]
PS: Is there a way to update from 4.0 to 4.2?

**Comment by derrellj** [comment]
Hi NewKidOnTheBlock,

You can trying running:
python3 -m pip install django~=4.0
Or
python -m pip install django~=4.0
This will update you to the latest version of django.
Then update requirement.txt with:
 python3 -m pip freeze > requirement.txt
Or
 python -m pip freeze > requirement.txt

Let me know if it works for you!

**Comment by NewKidOnTheBlock** [comment]
Oops, my bad. I was talking about receiving an updated copy of the _Django for Beginners_ book as I'm still using 4.0 which has some errors in it.

**Comment by wsvincent** [comment]
If you purchased the book through Gumroad you have access to the latest version. Btw thank you for pointing out the typo there. Fixed for the next edition.
