### ISSUE TITLE
{% url 'logout' %} 405 error

### ISSUE THREAD

**Issue by sartzsche** [wsvincent/djangoforbeginners#184]
Using **only** `{% url 'logout' %}` for user log out is deprecated.

A form with POST method must be used:

```
<form action="{% url 'logout' %}" method="post">{% csrf_token %}
   <button type="submit">Log out</button>
</form>
```

**Comment by wsvincent** [comment]
Yes, correct! This is something I'm updating for the next edition. Thank you for raising the issue.
