### ISSUE TITLE
typos pages 103 and 105

### ISSUE THREAD

**Issue by jbeckermsu** [wsvincent/djangoforbeginners#185]
p. 103: I believe the command should read:

(.venv) $ python -m pip install "environs[django]==9.5.0"

p. 105: I believe the command should read:

(.venv) $ python -m pip install "psycopg[binary]==3.1.8"

Additional comment: While the change to the command on p. 105 cleared one error, I did receive the following error that I am trying to resolve:

Collecting psycopg[binary]==3.1.8
  Using cached psycopg-3.1.8-py3-none-any.whl (167 kB)
Requirement already satisfied: typing-extensions>=4.1 in c:\users\jbeck\learningdjango\message-board\.venv\lib\site-packages (from psycopg[binary]==3.1.8) (4.9.0)
Requirement already satisfied: tzdata in c:\users\jbeck\learningdjango\message-board\.venv\lib\site-packages (from psycopg[binary]==3.1.8) (2023.4)
INFO: pip is looking at multiple versions of psycopg[binary] to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement psycopg-binary<=3.1.8,>=3.1.6; extra == "binary" (from psycopg[binary]) (from versions: 3.1.12, 3.1.13, 3.1.14, 3.1.15, 3.1.16, 3.1.17, 3.1.18)
ERROR: No matching distribution found for psycopg-binary<=3.1.8,>=3.1.6; extra == "binary"

**Comment by derrellj** [comment]
Thanks

**Comment by wsvincent** [comment]
Thank you for this issue. Updated for future issues. The new version of psycopg is the one to use, as you found. I still recommend the binary version for trying things out as it is much simpler.
