### ISSUE TITLE
stucked in ch8 

### ISSUE THREAD

**Issue by samyrtusna** [wsvincent/djangoforbeginners#187]
in ch8 in log out section a followed the book step by step , finaly when I try to logout I get and error message : HTTP ERROR 405.
I'm using django version 5.0.3 . so how can I fix this issue?

**Comment by thediogostein** [comment]
Same here, but I found a solution.
You need to create a form and use method='post'
Here are detailed instructions: 
https://stackoverflow.com/questions/77928535/django-can-login-but-cant-logout-405-method-not-allowed
