### ISSUE TITLE
Error in test_post_detail_view

### ISSUE THREAD

**Issue by eliumoraes** [wsvincent/djangoforbeginners#35]
I'm reading the chapter 5 of the book and I got an error in the test_post_detail_view class, so I come here to compare my file with the original and it has the same problem. I believe the test file cannot create the post and is getting an http 404 response. See the results:

```
$ blog python manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
.F..
======================================================================
FAIL: test_post_detail_view (blog.tests.BlogTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/eliu/programas/blog/blog/tests.py", line 41, in test_post_detail_view
    self.assertEqual(response.status_code, 200)
AssertionError: 404 != 200

----------------------------------------------------------------------
Ran 4 tests in 0.437s

FAILED (failures=1)
Destroying test database for alias 'default'...

```

PS: I'm reading the 2020 version of the book.

**Comment by eliumoraes** [comment]
I managed to find the error. My code was missing a '/':

My code:
`path('post/<int:pk>', BlogDetailView.as_view(), name='post_detail'),`

The correct code:
`path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),`

**Comment by wsvincent** [comment]
Glad you found it! I've made the same mistake many times myself.
