### ISSUE TITLE
Problem with reseting password via email.

### ISSUE THREAD

**Issue by walkersorlie** [wsvincent/djangoforbeginners#4]
Hi Will,

I am trying to implement the packaged Django authorization stuff (change password, reset password etc.). I have included the `django.contrib.auth.urls` in my URLconf, and the views are working up until the password_reset_confirm view. I recieve the email with a reset password link, but when I paste in the URL and try to go there, Django seems to start url matching for `registration/reset/THE_ID/THE_TOKEN/` (as it should), but then changes to try matching for `registration/reset/<THE_ID>/set-password` and throws `NoReverseMatch at /registration/reset/THE_ID/set-password/`. Any ideas of what's going on?

Thanks,
Walker

**Comment by wsvincent** [comment]
Hmm, late viewing this. The code in this repo works so it seems like a subtle typo. Often the templates are to blame for NoReverseMatch errors. Let me know via email will@wsvincent.com if you're still struggling with this.
