### ISSUE TITLE
Link to 'official source code' directs to the wrong chapter

### ISSUE THREAD

**Issue by DaveParr** [wsvincent/djangoforbeginners#52]
Hi,

First off, thanks a tonne for the book. Just finished it, thought it was brilliant.

Having worked dedicatedly though all the chapters, I found an _extremely_ trivial thing that may not even be a bug. In my copy of the epub, this para:

> Here’s what the updated base.html file should look like. Generally you should type all code examples yourself but as this is one is quite long and error-prone, it’s recommended to copy and paste from the official source code.

Link to source code at: https://github.com/wsvincent/djangoforbeginners/tree/master/ch10-bootstrap

Obviously, all that's happened is the chapters have moved around, and it's likely that your current print has already got a fix, but seeing as I bought the book only a month or two back from your website, I thought it could be possible that your build process hasn't caught that change, and _might_ still be printing the old link.

Still, this gives me a chance to say thanks for writing the book anyway, I've found it really useful. I've started my own hobby project based on in this morning, and am also looking at getting your 'Django for proffesionals' in a little while :)

**Comment by wsvincent** [comment]
Hi Dave,

Thanks for the comment. My bad as I updated the chapters for the 3.1 version that comes out shortly. I appreciate you writing in. 

-Will
