### ISSUE TITLE
Password change page throwing 404 error!

### ISSUE THREAD

**Issue by baremetals** [wsvincent/djangoforbeginners#53]
http://127.0.0.1:8000/users/password_change/

this page is giving me an error code. the Book said nothing needed to be done just go to that page logged in and should work but that page doesn't work for me. what could be causing this issue?

**Comment by wsvincent** [comment]
Hi @baremetals,

Hmm, I'm not sure unfortunately. I actually for the 3.1 update changed the default app to be named `accounts` and the corresponding URL route as well to be `/accounts/password_change/` to match default Django auth patterns.

If you have the ebook version you can see the new text and source code in the repo. If you're still stuck, let me know and we'll sort it out. Closing this comment for now.

**Comment by baremetals** [comment]
Oh nah it was me, typo or something. I finished the book already great book. I got all 3 series.

Get Outlook for iOS
 --------------------------------

**Comment by wsvincent** [comment]
Cool, no worries!
