### ISSUE TITLE
Cannot get pipenv to work on Windows 10 under PowerShell 5.1

### ISSUE THREAD

**Issue by sockduct** [wsvincent/djangoforbeginners#58]
Hi Will.  I'm working through this book and it's good - thank you for writing it!  I wanted to pass along some feedback and I'm not sure if this is the right place to do it - if not, please let me know.  When I use pipenv on PowerShell under Windows 10 it doesn't seem to work.  I tried Googling a little to no avail.  Please note though that I can work around this by using "manual" virtual environments (python -m venv ...) and pip freeze > requirements.txt for Heroku to work right.

In order to show where this is breaking, I start at the beginning of Chapter 2.  I do each step in Ubuntu 20.04.1, bash and Windows 10, PowerShell v5.1:

Note:  Both operating systems are using Python 3.8 (but differing minor versions) and pipenv version 2020.11.15.

Windows:
```
pipenv install django~=3.1.0
pipenv shell  # different result
```
In Windows, it creates a second virtual environment:
```
Creating a virtualenv for this project...
Pipfile: C:\Users\jsmall\Documents\Projects-NB\testing\django0\Pipfile
Using C:/Program Files (x86)/Python38-32/python.exe (3.8.1) to create virtualenv...
[=== ] Creating virtual environment...created virtual environment CPython3.8.1.final.0-32 in 1737ms
  creator CPython3Windows(dest=C:\Users\jsmall\.virtualenvs\django0-2fXYcGpM, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\jsmall\AppData\Local\pypa\virtualenv)
    added seed packages: pip==20.3.3, setuptools==51.1.2, wheel==0.36.2
  activators BashActivator,BatchActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

Successfully created virtual environment!
Virtualenv location: C:\Users\jsmall\.virtualenvs\django0-2fXYcGpM
Launching subshell in virtual environment...
```
Since pipenv created a second virtual environment, Django isn't installed here:
```
C:\Users\jsmall\Documents\Projects-NB\testing\django0> gcm django-admin
gcm : The term 'django-admin' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

Ubuntu:
```
pipenv install django~=3.1.0
pipenv shell  # different result
```
In Ubuntu I get:
```
Launching subshell in virtual environment...

small@ubuntuvm:~/pydev/django1<2000>$  . /home/small/.local/share/virtualenvs/django1-xQq5mSY4/bin/activate
(django1) small@ubuntuvm:~/pydev/django1<2000>$ which django-admin
/home/small/.local/share/virtualenvs/django1-xQq5mSY4/bin/django-admin
```

**Comment by sockduct** [comment]
Hi Will - I feel I should mention a few more details on this.  I opened up an issue on the pipenv repo on January 26, 2021:
https://github.com/pypa/pipenv/issues/4601

So far I haven't gotten a response, but there's a very long list of issues.  When I first heard about pipenv I was excited.  After all, it was by Kenneth Reitz, the creator of requests.  However, even when I watched his overview at PyCon 2018 (https://www.youtube.com/watch?v=GBQAKldqgZs) I noticed it was on a Mac.  Also, I'm sure you've noticed at PyCon that it's a sea of Macs with the rare Windows system.  I have made several attempts to use pipenv, but each time I ran into problems and was unable to resolve them.  My impression is that Windows is not a first class platform for this package.  Pipenv seems decent for Linux or macOS - when I use it on Ubuntu it works fine, but it's definitely not a replacement for pip and virtual environments.  I've heard a lot about poetry too, but so far haven't tried it out.

**Comment by morf23** [comment]
Couldn't use pipenv as well; working with Windows 10. 

Instead, make first a virtual environment:

`C:\Users\username\Desktop\name_of_your_folder>python -m venv name_of_env`

Then activate it:

`C:\Users\username\Desktop\name_of_your_folder\name_of_env\Scripts>activate`

That should do the trick.

**Comment by wsvincent** [comment]
Hi @sockduct and @morf23, I'm sorry to hear about these issues. Glad that creating the virtual environment FIRST seems to help. I'm actually switching to Pip for the 3.2 update as I think it's a bit easier. Pipenv is great but the number of edge cases means I think regular ole Pip wins out.

Thank you both for the comments.
