### ISSUE TITLE
custom fields in CustomUserCreationForm not showing up in Django admin app

### ISSUE THREAD

**Issue by dm-wyncode** [wsvincent/djangoforbeginners#6]
Hello,

I am enjoying following the examples in _Django for Beginners_.

One part has confused me, however.

I was expecting a custom field to show up in the form to add an instance of a custom user in the Django admin. I thought I had made an error that I could not spot, so I tried running the code in this repo.

When I click on "Add User" with a URL of "/admin/users/customuser/add/" I still only see the default fields:

![screenshot236](https://user-images.githubusercontent.com/17745063/53989031-f8af1d80-40f2-11e9-8458-032eb7c5a45d.png)

I expected the code in these lines to add a field for "age": https://github.com/wsvincent/djangoforbeginners/blob/master/ch8-custom-user-model/users/forms.py#L7-L11

because the form is assigned to "add_form" in this code:
https://github.com/wsvincent/djangoforbeginners/blob/master/ch8-custom-user-model/users/admin.py#L9

Am I misunderstanding that the fields should show up in the included Django admin app, or will this field only show up in a custom sign-up form that is explained in the next chapter?

Thanks again for writing an excellent book for beginners.

P.S. I learned about the book from the _Talk Python to Me_ podcast.

**Comment by dm-wyncode** [comment]
I think I have answered my own question after a lot of perusing Stackoverflow questions and the Django docs:

* [Modifying Django UserCreationForm](https://stackoverflow.com/a/6684949/1913726)
* [Customizing authentication in Django](https://docs.djangoproject.com/en/2.1/topics/auth/customizing/) (Search for "add_fieldsets" in the page.)

I changed [this code](https://github.com/wsvincent/djangoforbeginners/blob/master/ch8-custom-user-model/users/admin.py) to this:

```python

    from django.contrib import admin
    from django.contrib.auth.admin import UserAdmin

    from .forms import CustomUserChangeForm, CustomUserCreationForm
    from .models import CustomUser


    class CustomUserAdmin(UserAdmin):
        add_form = CustomUserCreationForm
        form = CustomUserChangeForm
        model = CustomUser
        list_display = ["email", "username", "age", "is_staff"]
        add_fieldsets = (
            (
                None,
                {
                    "classes": ("wide",),
                    "fields": ("username", "password1", "password2", "age"),
                },
            ),
        )


    admin.site.register(CustomUser, CustomUserAdmin)

```

and now URL "/admin/users/customuser/add/" appears like this. I was able to successfully create a new instance of a custom user with this form.

![screenshot240](https://user-images.githubusercontent.com/17745063/54031274-4e7bd800-417c-11e9-85be-7a47fbaac9e5.png)

**Comment by craigmaloney** [comment]
Actually this could stand to be highlighted because it wasn't until I stumbled across this that I realized what I was doing wrong (the `add_fieldsets` parameter in particular)

**Comment by doyleisgod** [comment]
I recently finished this book and started working to extend my understanding this post was a great help.

**Comment by evaldasJankus** [comment]
@dm-wyncode Thank you, you saved me from a lot of thinking or reading, I am currently using this book to learn Django, and was crossing the Chapter 9, when I got this thought, while during the tutorial. Finished tutorial but when doing that I was all the time thinking about this. Thanks again.

**Comment by FlameLine** [comment]
@dmmfll, thank you so much!
_Django for beginners_ squad 🤙
Also, here is a quick image explanation (maybe someone will find it helpful):
![image](https://github.com/wsvincent/djangoforbeginners/assets/62658287/2fb8bb4f-2d4e-4068-8fdf-cad99e15bb67)
