### ISSUE TITLE
Chapter 16: Deployment ERROR

### ISSUE THREAD

**Issue by mohammadekhosravi** [wsvincent/djangoforbeginners#60]
Hi Vincent.
In version 3.1 of the book, chapter 16 deployment on Heroku because we use bootstrap and don't have any static files, we create static/css and so on without any file inside them.
it seems like git doesn't track empty directories and so when we gonna deploy on Heroku and it run the <code>python manage.py collectstatic</code> there's an error.
i use <a href="https://stackoverflow.com/a/36676953">THIS</a> to solve it and it seems like the right thing to let you know.
Thanks for Great Book.

P.S: Sorry for bad English I'm not a native speaker.

**Comment by wsvincent** [comment]
Hi @mohammadekhosravi , This is a very good point! I think the simplest approach is to just add an empty file to each. I've updated the text so the newest version of the book reflects this change.

Thanks again for pointing it out!

**Comment by mnoah66** [comment]
Hi William,

Looks like you maybe updated chapters 5,6,7?  But chapter 16 still does not have a step to add an empty file into one of static/css, static/js, or static/images.  I am looking at page 261 of the PDF version.

Great book!
Martin
