### ISSUE TITLE
pip3 install pipenv for Windows

### ISSUE THREAD

**Issue by john3641** [wsvincent/djangoforbeginners#7]
I first attempted to work through the book (for 2.1) on a Linux system, but ran into too many glitches when I tried to install pipenv, even after trying stackoverflow and other informative websites.  So I decided to start all over in Windows.  (I don't have a Mac.)   I've installed Python 3.7.1 on Windows, but when I try the pip3 install pipenv command on top of page 17 I get error.   What would be the Windows equivalent?

**Comment by wsvincent** [comment]
Does this help? https://stackoverflow.com/questions/49740073/installation-of-pipenv-on-windows-fails
