### ISSUE TITLE
Why are you using "post_detail" instead of "post" in home.html?

### ISSUE THREAD

**Issue by Steve-Dusty** [wsvincent/djangoforbeginners#72]
In chapter 6, in templates/home.html, why are you using  `{% url 'post_detail' post.pk %}` instead of `{% url 'post' post.pk %}` when we want to redirect to the path `post/int` not `post_detail/int`?

**Comment by wsvincent** [comment]
Hi Steve, That's because we want the URL link to be to the individual blog post, which uses the detail view. Only it has the `post.pk` included. If we just used `post` it would be the listview. And no `pk` needed for the URL. I admit it's confusing the first few times around.
