### ISSUE TITLE
Chapter 7 repeated words

### ISSUE THREAD

**Issue by MenasheKoren** [wsvincent/djangoforbeginners#90]
Hi,

In chapter 7's [config/settings.py](https://github.com/wsvincent/djangoforbeginners/blob/ad9939a8af32d38e0caee3102979db5f0b00237d/ch7-blog-app-with-users/config/settings.py) line 114 has STATIC_ROOT twice. 
`STATIC_ROOT = STATIC_ROOT = str(BASE_DIR.joinpath('staticfiles')) # new` 

Is that necessary?

**Comment by wsvincent** [comment]
That's a typo that has since been fixed. No need to duplicate! Thx for letting me know.
