### ISSUE TITLE
Chapter 2: Hello World App - master is now main

### ISSUE THREAD

**Issue by johnpilbeam** [wsvincent/djangoforbeginners#91]
On pages 30 (screenshot) and 31 (command), the branch is still shown as _master_, e.g. 
`(helloworld) $ git push -u origin master`
All new projects set up via  https://github.com/new now have _main_ as the default branch.

**Comment by wsvincent** [comment]
Hi @johnpilbeam ,

You are correct! I'm finishing the 3.2 update and this is one of the changes. Main is a much better choice than master for many reasons. I'm pleased GitHub has that default. Django has switched over itself. I've done so for my own projects. And the books will for the 3.2 updates.

Cheers,

Will

**Comment by johnpilbeam** [comment]
Hi @wsvincent ,

That's great news! Thanks for letting me know that this is already in the works. I totally agree about the change to main. I look forward to the updated book. Thanks for your continued work on the books - and the podcast and newsletter.

Best,
John
