### ISSUE TITLE
"Your connection is not private" error on password reset following the steps in Chapter 12: Email

### ISSUE THREAD

**Issue by JakobLS** [wsvincent/djangoforbeginners#98]
Following the steps in Chapter 12: Email, can you confirm that the link received by email upon password reset works as intended? @wsvincent  

I'm getting the following error. 

> **Your connection is not private**
> NET::ERR_CERT_COMMON_NAME_INVALID

The link works as intended when outputting it in the console though. 

I opened an [SO question](https://stackoverflow.com/questions/69585864/neterr-cert-common-name-invalid-error-on-gcp-hosted-django-site-on-email-reset) as well if you want more context. 

Thanks for writing an otherwise great book.

**Comment by wsvincent** [comment]
Hi Jakob,

Thanks for your email. I see the SO question you note. My guess would also be around SSL on your host. I'm pretty sure it's not a Django or SendGrid issue. As I cover Heroku, not GCP App Engine, in the book I'm going to close this for now. Do reopen or let me know if it ends up being a Django/SendGrid issue.

-Will
